
#Configurations of the world generator.
[worldgen]
	#The rarity of well structures in the midnight. Higher values increase rarity. When 0, well structures are disabled. Default: 1
	#Range: > 0
	well_structure_rarity = 1
	#The rarity of rift heap structures. Higher values increase rarity. When 0, rift structures are disabled. Default: 5
	#Range: > 0
	rift_structure_rarity = 5
	#The rarity of molten crater structures in the midnight. Higher values increase rarity. When 0, crater structures are disabled. Default: 1
	#Range: > 0
	crater_structure_rarity = 1
	#The rarity of shadowroot guardtower structures in the midnight. Higher values increase rarity. When 0, guardtower structures are disabled. Default: 1
	#Range: > 0
	guardtower_structure_rarity = 1

#All the options that can only be set on the server.
[logic]
	#Sets if random lightning effects appear in the midnight or not. Default: true
	random_lightnings = true
	#Allows rifters to teleport to players when they aren't being looked at. Default: true
	allow_rifter_teleport = true
	#Allows rifters to capture nametagged entities and drag them into rifts. Default: true
	rifter_capture_named_animal = true
	#If true, rifts are open during the day. If false, rifts are only open at nighttime. Default: false
	rifts_open_at_daytime = false
	#The rarity that rifts spawn rifters. Larger numbers increase rarity. If 0, rifters don't spawn from rifts. Default: 1000
	#Range: > 0
	rifter_spawn_rarity = 1000
	#If true, hunters will attack tamed skulks. Default: true
	hunters_attack_tamed_skulks = true
	#The maximum amount of rifters that spawn from a rift. Default: 2
	#Range: 1 ~ 10
	max_rifter_by_rift = 2
	#Allows rifters to capture tamed entities and drag them into rifts. Default: false
	rifter_capture_tamed_animal = false
	#The chance in percents to take a small amount of damage when obtaining a bladeshroom cap. If 0, this is disabled. Default: 5
	#Range: 0 ~ 100
	bladeshroom_damage_chance = 5
	#If true, players will respawn in Midnight after dying in the dimension. Default: false
	can_respawn_in_midnight = false
	#If true, dark pearls can be used to make rifts. Default: true
	rifts_from_dark_pearls = false
	#Allows the lightning in Midnight to burn blocks and do damage to entities. Default: false
	allow_lightning_damage = false
	#The percent chance (from 0 to 100) for a rifter to spawn naturally. If 0, no rifters spawn at all. Default: 75
	#Range: 0 ~ 100
	natural_rifter_spawn_rarity = 50
	#The percent chance (from 0 to 100) for a rifter to make an ambience sound at any time. Default: 75
	#Range: 0 ~ 100
	rifter_ambience_chance = 75

