
["Nasty Skeleton"]
	#Minimum health
	#Range: 4.0 ~ 5000.0
	MinHealth = 20.0
	#Maximum health
	#Range: 100.0 ~ 5000.0
	MaxHealth = 100.0
	#Minimum Distance
	#Range: 0.0 ~ 1280000.0
	MinDistance = 100000.0
	#Maximum Distance
	#Range: 0.0 ~ 1280000.0
	MaxDistance = 1000000.0
	#Spawn in Biome weight
	#Range: 0 ~ 200
	SpawnBiome = 100
	#Spawn in Feature weight
	#Range: 0 ~ 20
	SpawnFeature = 5
	#Spawn in Dungeon weight
	#Range: 0 ~ 200
	SpawnDungeon = 100
	#Spawn light level (use 7 to be same as normal skeletons)
	#Range: 0 ~ 15
	SpawnLightLevel = 7
	#Arrow Damage Multiplier (damage to skeleton)
	#Range: 0.0 ~ 1.0
	ArrowDamageMultiplier = 0.5
	#Explosive Arrow cause Armor to drop
	ExplosiveArrowOnArmor = true
	#Explosive Arrow cause Block to drop
	ExplosiveArrowOnBlock = true
	#Explosive Arrow cause Shield to drop
	ExplosiveArrowOnShield = false
	#Explosive Arrow strength
	#Range: 1.0 ~ 1500.0
	ExplosiveArrowStrength = 8.0
	#Virus Distance for spreading
	#Range: 0.0 ~ 20.0
	VirusDistance = 5.0
	#Virus Chance for spreading
	#Range: 0.0 ~ 1.0
	VirusChance = 0.02
	#Spawn type based on Tempature
	SpawnTempBased = false
	#Spawn weights (Green,Red,Purple,Cyan,Orange,Yellow)
	SpawnVariantWeights = "5,5,5,5,5,1"
	#Biome adjustments (biome,variant,hp,speed)
	BiomeAdjustments = "minecraft:plains,*,-0.2,0.2;minecraft:swamp,0,0.2,0.0;minecraft:swamp,*,0.1,-0.1;minecraft:badlands,*,0.3,0.3;minecraft:dark_forest_hills,*,0.3,0.3"

["Nasty Wolf"]
	#Virus Mode
	#Allowed Values: OFF, WILD, UNNAMED
	VirusMode = "WILD"
	#Virus Chance for spreading
	#Range: 0.0 ~ 1.0
	VirusChance = 0.25

