
#
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]
	#
	#Range: 0.0 ~ 1.0
	fanParticleDensity = 0.5
	#
	#Offset the overlay from goggle- and hover- information by this many pixels on the Y axis; Use /create overlay
	#Range: > -2147483648
	overlayOffsetY = 0
	#
	#Offset the overlay from goggle- and hover- information by this many pixels on the X axis; Use /create overlay
	#Range: > -2147483648
	overlayOffsetX = 20
	#
	#Log a stack-trace when rendering issues happen within a moving contraption.
	explainRenderErrors = false
	#
	#Use modern OpenGL features to drastically increase performance.
	experimentalRendering = true
	#
	#Show colourful debug information while the F3-Menu is open.
	enableRainbowDebug = true
	#
	#Show item descriptions on Shift and controls on Ctrl.
	enableTooltips = true
	#
	#Display a tooltip when looking at overstressed components.
	enableOverstressedTooltip = true

	#
	#Ponder settings
	[client.ponder]
		#
		#Slow down a ponder scene whenever there is text on screen.
		comfyReading = false

	#
	#Settings for the Placement Assist
	[client.placementAssist]
		#
		#Change the size of the Indicator by this multiplier
		#Range: 0.0 ~ 3.4028234663852886E38
		indicatorScale = 1.0
		#
		#What indicator should be used when showing where the assisted placement ends up relative to your crosshair
		#Choose 'NONE' to disable the Indicator altogether
		#Allowed Values: TEXTURE, TRIANGLE, NONE
		indicatorType = "TEXTURE"

