
#General Settings
[general]
	#If set to true, dungeon crawl will use the old dungeon registry name. This will prevent errors when playing in worlds that have been used with Dungeon Crawl 1.4.0 or earlier before. If that is not the case, DO NOT activate this!
	compatiblity_mode = false

#Dungeon Settings
[dungeon]
	#If you dont like the fact that the dungeons contain lots of mob spawners, set this to true! Mobs will get spawned manually during the dungeon generation then. Note that this is a lot more performance demanding than enabling spawners. (Which also depends on the mob spawn rate)
	no_spawners = false
	#This value defines how many mobs do get spawned manually during the generation. (if no_spawners = true, there is no effect otherwise)
	#Range: 0.001 ~ 1.0
	mob_spawn_rate = 0.05
	#The number of different entities per spawner. Increasing the number increases the diversity of the monster equipment.
	#Range: 1 ~ 128
	spawner_entities = 8
	#The minumum amount of rooms for each dungeon layer.
	#Range: 0 ~ 24
	layer_min_additions = 5
	#The amount of extra rooms per dungeon layer. A random number in the range [0 ~ layer_extra_additions-1] will be used.
	#Range: 1 ~ 24
	layer_extra_additions = 6
	#Defines if bridges should be used in dungeons. (Bridges are built if there is a certain amout of air under a corridor segment.
	build_bridges = true
	#If set to true, the dungeon generation will ignore the biome blacklist and generate dungeons in any overworld biome.
	ignore_overworld_blacklist = false
	#The Probability of a spawner entity having a shield in the offhand.
	#Range: 0.01 ~ 1.0
	shield_probability = 0.25
	#Determines if vanilla spawners or modified spawners with armor, weapons etc... should be used.
	use_vanilla_spawners = false
	#The size of the dungeons. (1 unit = 8 blocks)
	#Range: 4 ~ 16
	size = 16

#World Generation Settings
[world_generation]
	#The probability of a dungeon getting generated on each fitting chunk.
	#Range: 1.0E-4 ~ 1.0
	dungeon_probability = 0.25
	#If set to true, the dungeon generation will ignore the dimension and use only the biome blacklists to determine generation eligibility.
	ignore_dimension = true

