
#Bit detection
[BitDetection]
	#If ShouldYellAt32BitUsers is set to true, this is the message that will be displayed to the user.
	Message = "You are using a 32 bit version of java. This is not recommended with this modpack."
	#Set to true to make itlt yell at people attempting to use 32x java for the modpack.
	ShouldYellAt32BitUsers = true

#Management of a dedicated server
[Server]
	#The name of the dedicated server to add.
	ServerName = "localhost"
	#The ip of the dedicated server to add.
	ServerIP = "127.0.0.1:25555"
	#Set to true to have a dedicated server added to the server list ingame. The server will not overwrite others servers.
	AddDedicatedServer = false

#Display
[Display]
	#Set to true to attempt to use the icon assigned to the modpack by the technic launcher. 
	#This will take priority over loadCustomIcon
	useTechnicIcon = false
	#Change this value to change the name of the MineCraft window
	windowDisplayTitle = "Craft to Exile [Dissonance]"
	#Set to true to attempt to get the display name of the pack of the info json file \nThis will take priority over windowDisplayTitle
	useTechnicDisplayName = true
	#Set to true to load a custom icon from config\itlt\icon.png
	loadCustomIcon = true

