
#General mod settings
[general]
	#Range: 1.0 ~ 30000.0
	tileEntityRenderRangeMax = 24.0
	tileEntityRenderLimitModdedOnly = true
	#Range: 1.0 ~ 30000.0
	entityRenderRangeMax = 64.0
	entityRenderLimitModdedOnly = true

