
[spawn]
	#UNDEAD MINER's spawn chance. Default=80. ----------
	#Range: 0 ~ 100
	undead_miner_chance = 0
	#IMMORTAL's spawn chance. Default=1. ---------------
	#Range: 0 ~ 100
	immortal_chance = 3
	#ROTTEN ESKIMO's spawn chance. Default=30. ---------
	#Range: 0 ~ 100
	rotten_eskimo_chance = 50
	#MUMMY's spawn chance. Default=50. -----------------
	#Range: 0 ~ 100
	mummy_chance = 0
	#FROSTBITTEN's spawn chance. Default=80. -----------
	#Range: 0 ~ 100
	frostbitten_chance = 80
	#SWAMPY's spawn chance. Default=80. ----------------
	#Range: 0 ~ 100
	swampy_chance = 80
	#DEAD BEARD's spawn chance. Default=3. -------------
	#Range: 0 ~ 100
	dead_beard_chance = 3
	#BURNED's spawn chance. Default=70. ----------------
	#Range: 0 ~ 100
	burned_chance = 70

