
#These options are only relevant to the client.
[client]
	#If enabled, the text overlay on waystones will no longer always render at full brightness.
	disableTextGlow = false
	#The y position of the warp button in the inventory.
	teleportButtonY = 60
	#The volume of the sound played when teleporting.
	#Range: 0.0 ~ 1.0
	soundVolume = 0.10000000149011612
	#The x position of the warp button in the inventory.
	teleportButtonX = 58
	#If enabled, a JourneyMap waypoint will be created when activating a waystone.
	createJourneyMapWaypoint = true
	#If enabled, activated waystones will not emit particles.
	disableParticles = false

