
#The new config sync is great, but common configs don't sync to clients. Therefore all synced options need to be in the server config, which is in your world directory. Hopefully at some point Forge will sync COMMON too so we don't need to split options so much.
[common]

	[common.worldgen]
		#Set to 'DEFAULT' to only generate the normally textured waystones. Set to 'MOSSY' or 'SANDY' to generate all as that variant. Set to 'BIOME' to make the style depend on the biome it is generated in.
		#Allowed Values: DEFAULT, MOSSY, SANDY, BIOME
		worldGenStyle = "BIOME"
		#Set to true if waystones should be added to the generation of villages.
		addVillageStructure = false
		#Approximate chunk distance between waystones generated freely in world generation. Set to 0 to disable generation.
		#Range: > 0
		worldGenFrequency = 0
		#The Name Generator will pick from these names until they have all been used, then it will generate random ones again.
		customWaystoneNames = []

